-- Expand CallStatus to mirror Twilio lifecycle more accurately.
ALTER TYPE "CallStatus" ADD VALUE IF NOT EXISTS 'RINGING';
ALTER TYPE "CallStatus" ADD VALUE IF NOT EXISTS 'IN_PROGRESS';
ALTER TYPE "CallStatus" ADD VALUE IF NOT EXISTS 'NO_ANSWER';
ALTER TYPE "CallStatus" ADD VALUE IF NOT EXISTS 'BUSY';
ALTER TYPE "CallStatus" ADD VALUE IF NOT EXISTS 'CANCELED';
ALTER TYPE "CallStatus" ADD VALUE IF NOT EXISTS 'FAILED';
